name: Release Rez Package

on:
  workflow_call:
    inputs:
      options-lin:
        required: false
        type: string
      options-win:
        required: false
        type: string
      options-mac:
        required: false
        type: string
jobs:
  rez-release-linux:
    runs-on: [self-hosted, Linux]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: release Rez package
        run: $REZ_ACTIVATOR rez release --no-latest --ignore-existing-tag ${{ inputs.options-lin }}
